// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8en-w8fUOrMmSYlTGlyYZaBSWM3uYVX0',
    appId: '1:446077732516:web:f171900435be0c3c230831',
    messagingSenderId: '446077732516',
    projectId: 'nesbyy-36b39',
    authDomain: 'nesbyy-36b39.firebaseapp.com',
    storageBucket: 'nesbyy-36b39.firebasestorage.app',
    measurementId: 'G-18S4XYJK3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc204OCa8ZQ4aqeMiVbL_55SajzYkLexg',
    appId: '1:446077732516:android:63b86ef11bff0e6a230831',
    messagingSenderId: '446077732516',
    projectId: 'nesbyy-36b39',
    storageBucket: 'nesbyy-36b39.firebasestorage.app',
  );
}
